import React, { useRef } from 'react';
import {
  Box,
  Container,
  Typography,
  Card,
  CardContent,
  Grid,
  Chip,
  Button,
  Paper,
  Alert,
  Stack
} from '@mui/material';
import { Download, ContentCopy, AutoAwesome, CheckCircle, WarningAmber, Bookmark, ArrowBack } from '../components/MuiIcons';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export default function StudySheetPage({ studySheet, providerUsed, onNewUpload }) {
  const printRef = useRef(null);

  if (!studySheet) return null;

  const handleDownloadPDF = async () => {
    const element = printRef.current;
    if (!element) return;
    try {
      const canvas = await html2canvas(element, { scale: 2, useCORS: true });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const imgWidth = 210;
      const pageHeight = 297;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;
      let position = 0;

      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      pdf.save(`${studySheet.title.replace(/\s+/g, '_')}_StudySheet.pdf`);
    } catch (e) {
      console.error('PDF export failed:', e);
      window.print();
    }
  };

  const handleCopyMarkdown = () => {
    const md = `# ${studySheet.title}\nSubject: ${studySheet.subject}\n\n## 🎯 Learning Objectives\n` +
      studySheet.learning_objectives.map(o => `- ${o}`).join('\n') + '\n\n## 💡 Key Concepts\n' +
      studySheet.key_concepts.map(c => `### ${c.concept}\n${c.description}`).join('\n\n') + '\n\n## 📖 Definitions\n' +
      studySheet.definitions.map(d => `- **${d.term}**: ${d.definition}`).join('\n') + '\n\n## ⚠️ Common Mistakes\n' +
      studySheet.common_mistakes.map(m => `- ${m}`).join('\n') + '\n\n## 📌 Revision Notes\n' +
      studySheet.revision_notes.map(r => `- ${r}`).join('\n') + '\n\n## 📝 Final Summary\n' + studySheet.final_summary;

    navigator.clipboard.writeText(md);
    alert('Study Sheet copied to clipboard as Markdown!');
  };

  return (
    <Container maxWidth="md" sx={{ py: 6 }}>
      {/* ACTION HEADER BAR */}
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Button startIcon={<ArrowBack />} onClick={onNewUpload} sx={{ color: 'text.secondary' }}>
          Upload Another Lecture
        </Button>
        <Stack direction="row" spacing={1.5}>
          <Button
            variant="outlined"
            size="small"
            startIcon={<ContentCopy />}
            onClick={handleCopyMarkdown}
            sx={{ borderColor: '#dadce0', color: 'text.primary' }}
          >
            Copy Markdown
          </Button>
          <Button
            variant="contained"
            color="primary"
            size="small"
            startIcon={<Download />}
            onClick={handleDownloadPDF}
          >
            Download PDF
          </Button>
        </Stack>
      </Box>

      {/* PRINTABLE STUDY SHEET CONTAINER */}
      <Paper
        ref={printRef}
        elevation={1}
        sx={{
          p: { xs: 3, md: 5 },
          borderRadius: 3,
          backgroundColor: '#ffffff',
          border: '1px solid #e0e0e0',
        }}
      >
        {/* HEADER SECTION */}
        <Box sx={{ borderBottom: '2px solid #f1f3f4', pb: 3, mb: 4 }}>
          <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 1.5 }}>
            <Chip label={studySheet.subject || 'Academic Lecture'} color="primary" size="small" sx={{ fontWeight: 600 }} />
            <Chip
              icon={<AutoAwesome style={{ fontSize: 14, color: '#1a73e8' }} />}
              label={`Generated by ${providerUsed || 'Mistral AI'}`}
              size="small"
              variant="outlined"
              sx={{ color: 'primary.main', borderColor: '#c2e7ff' }}
            />
          </Stack>
          <Typography variant="h3" sx={{ fontWeight: 700, color: 'text.primary', letterSpacing: '-0.01em', mb: 1 }}>
            📘 {studySheet.title}
          </Typography>
          <Typography variant="caption" sx={{ color: 'text.secondary', display: 'block' }}>
            LectureCapture AI v2 — Exam Preparation & Revision Sheet
          </Typography>
        </Box>

        {/* 1. LEARNING OBJECTIVES */}
        {studySheet.learning_objectives?.length > 0 && (
          <Box sx={{ mb: 4 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, color: 'text.primary', mb: 2 }}>
              🎯 Learning Objectives
            </Typography>
            <Paper variant="outlined" sx={{ p: 2.5, backgroundColor: '#f8f9fa', borderColor: '#e0e0e0', borderRadius: 2 }}>
              <Grid container spacing={1.5}>
                {studySheet.learning_objectives.map((obj, i) => (
                  <Grid item xs={12} key={i} sx={{ display: 'flex', alignItems: 'flex-start', gap: 1.5 }}>
                    <CheckCircle sx={{ color: '#1e8e3e', fontSize: 20, mt: 0.2 }} />
                    <Typography variant="body2" sx={{ color: 'text.primary', fontWeight: 500 }}>
                      {obj}
                    </Typography>
                  </Grid>
                ))}
              </Grid>
            </Paper>
          </Box>
        )}

        {/* 2. KEY CONCEPTS */}
        {studySheet.key_concepts?.length > 0 && (
          <Box sx={{ mb: 4 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, color: 'text.primary', mb: 2 }}>
              💡 Key Concepts
            </Typography>
            <Grid container spacing={2}>
              {studySheet.key_concepts.map((kc, i) => (
                <Grid item xs={12} sm={6} key={i}>
                  <Card variant="outlined" sx={{ height: '100%', borderColor: '#e0e0e0' }}>
                    <CardContent sx={{ p: 2.5 }}>
                      <Typography variant="subtitle1" sx={{ fontWeight: 600, color: 'primary.main', mb: 1 }}>
                        {kc.concept}
                      </Typography>
                      <Typography variant="body2" sx={{ color: 'text.secondary', lineHeight: 1.6 }}>
                        {kc.description}
                      </Typography>
                    </CardContent>
                  </Card>
                </Grid>
              ))}
            </Grid>
          </Box>
        )}

        {/* 3. DEFINITIONS */}
        {studySheet.definitions?.length > 0 && (
          <Box sx={{ mb: 4 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, color: 'text.primary', mb: 2 }}>
              📖 Key Definitions
            </Typography>
            <Paper variant="outlined" sx={{ overflow: 'hidden', borderColor: '#e0e0e0', borderRadius: 2 }}>
              {studySheet.definitions.map((def, i) => (
                <Box
                  key={i}
                  sx={{
                    p: 2,
                    borderBottom: i < studySheet.definitions.length - 1 ? '1px solid #e0e0e0' : 'none',
                    '&:nth-of-type(even)': { backgroundColor: '#f8f9fa' },
                  }}
                >
                  <Typography variant="subtitle2" sx={{ fontWeight: 600, color: 'text.primary', display: 'inline', mr: 1 }}>
                    {def.term}:
                  </Typography>
                  <Typography variant="body2" sx={{ color: 'text.secondary', display: 'inline' }}>
                    {def.definition}
                  </Typography>
                </Box>
              ))}
            </Paper>
          </Box>
        )}

        {/* 4. FORMULAE & EQUATIONS (If present) */}
        {studySheet.formulae && studySheet.formulae.length > 0 && (
          <Box sx={{ mb: 4 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, color: 'text.primary', mb: 2 }}>
              ⚙️ Formulae & Syntax Rules
            </Typography>
            <Grid container spacing={2}>
              {studySheet.formulae.map((f, i) => (
                <Grid item xs={12} key={i}>
                  <Paper variant="outlined" sx={{ p: 2, backgroundColor: '#f8f9fa', borderLeft: '4px solid #1a73e8', borderRadius: 2 }}>
                    <Typography variant="subtitle2" sx={{ fontWeight: 600, color: 'text.primary', mb: 0.5 }}>
                      {f.name}
                    </Typography>
                    <Box
                      component="pre"
                      sx={{
                        p: 1.5,
                        backgroundColor: '#202124',
                        color: '#8ab4f8',
                        borderRadius: 1.5,
                        fontFamily: 'monospace',
                        fontSize: '0.875rem',
                        overflowX: 'auto',
                        my: 1,
                      }}
                    >
                      {f.expression}
                    </Box>
                    <Typography variant="caption" sx={{ color: 'text.secondary', fontStyle: 'italic' }}>
                      Usage: {f.context}
                    </Typography>
                  </Paper>
                </Grid>
              ))}
            </Grid>
          </Box>
        )}

        {/* 5. EXAMPLES */}
        {studySheet.examples?.length > 0 && (
          <Box sx={{ mb: 4 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, color: 'text.primary', mb: 2 }}>
              🧪 Examples Discussed
            </Typography>
            <Paper variant="outlined" sx={{ p: 2.5, backgroundColor: '#f8f9fa', borderColor: '#e0e0e0', borderRadius: 2 }}>
              <Stack spacing={1.5}>
                {studySheet.examples.map((ex, i) => (
                  <Typography key={i} variant="body2" sx={{ color: 'text.primary', lineHeight: 1.6 }}>
                    • {ex}
                  </Typography>
                ))}
              </Stack>
            </Paper>
          </Box>
        )}

        {/* 6. COMMON MISTAKES & EXAM TRAPS */}
        {studySheet.common_mistakes?.length > 0 && (
          <Box sx={{ mb: 4 }}>
            <Alert
              severity="warning"
              icon={<WarningAmber />}
              sx={{ borderRadius: 2 }}
            >
              <Typography variant="subtitle1" sx={{ fontWeight: 600, mb: 0.5 }}>
                Common Mistakes & Exam Traps
              </Typography>
              <Stack spacing={0.5}>
                {studySheet.common_mistakes.map((m, i) => (
                  <Typography key={i} variant="body2">
                    • {m}
                  </Typography>
                ))}
              </Stack>
            </Alert>
          </Box>
        )}

        {/* 7. REVISION NOTES */}
        {studySheet.revision_notes?.length > 0 && (
          <Box sx={{ mb: 4 }}>
            <Typography variant="h6" sx={{ fontWeight: 600, color: 'text.primary', mb: 2 }}>
              📌 High-Yield Revision Bullets
            </Typography>
            <Paper variant="outlined" sx={{ p: 2.5, backgroundColor: '#e8f0fe', borderColor: '#c2e7ff', borderRadius: 2 }}>
              <Grid container spacing={1}>
                {studySheet.revision_notes.map((rn, i) => (
                  <Grid item xs={12} key={i} sx={{ display: 'flex', gap: 1 }}>
                    <Bookmark sx={{ color: 'primary.main', fontSize: 18, mt: 0.3 }} />
                    <Typography variant="body2" sx={{ color: 'primary.dark', fontWeight: 500 }}>
                      {rn}
                    </Typography>
                  </Grid>
                ))}
              </Grid>
            </Paper>
          </Box>
        )}

        {/* 8. FINAL SUMMARY */}
        {studySheet.final_summary && (
          <Box sx={{ p: 3, backgroundColor: '#f8f9fa', borderRadius: 2, border: '1px solid #e0e0e0' }}>
            <Typography variant="subtitle1" sx={{ fontWeight: 600, color: 'text.primary', mb: 1 }}>
              📝 Executive Summary
            </Typography>
            <Typography variant="body2" sx={{ color: 'text.secondary', lineHeight: 1.7, fontStyle: 'italic' }}>
              "{studySheet.final_summary}"
            </Typography>
          </Box>
        )}
      </Paper>
    </Container>
  );
}
